[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
image = "0.25.10"
rayon = "1.12.0"
tokio = { version = "1.53.1", features = ["full"] }
tower = { version = "0.5.3", features = ["limit", "load-shed", "timeout"] }
tower-http = { version = "0.7.1", features = ["fs"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.dev]
opt-level = 3
lto = "off"  # for faster compile time
panic = "unwind"  # for joinable panicked threads

[profile.release]
lto = "fat"
panic = "unwind"
